const Data = [
  {
    id: 1,
    title: "B52",
    category: "drink",
    img: "./images/B52.jpg",
    desc: "Coffee liqueur, Baileys, Grand Marnier",
    url: "",
  },
  {
    id: 2,
    title: "Whiskey Sour",
    category: "drink",
    img: "./images/WhiskeySour.webp",
    desc: "4 Whiskey, 4 Sweet&Sour, 2 Syrub, Lemon, Egg White, Orange , Cherry",
    url: "",
  },
  {
    id: 3,
    title: "Margarita",
    category: "drink",
    img: "./images/margarita.jpg",
    desc: "4 Tequila, 4 Sweet&Sour, 2 Triple sec, Lime",
    url: "",
  },
  {
    id: 4,
    title: "Fried Rice",
    category: "food",
    img: "./images/FriedRice.jpg",
    desc: "Rice, Meat, Soy Sauce",
    url: "",
  },
  {
    id: 5,
    title: "Ice Cream",
    category: "dessert",
    img: "./images/icecream.jpg",
    desc: "Jenny Ice-cream",
    url: "",
  },
  {
    id: 6,
    title: "CheeseCake",
    category: "dessert",
    img: "./images/cheesecake.webp",
    desc: "Salt, Cheesecake Factory",
    url: "",
  },
  {
    id: 7,
    title: "Mojito",
    category: "drink",
    img: "./images/mojito.webp",
    desc: "4 Rum, 2 Lime Rose, 2 Syrup, 2 Sourmix, Lime, Mint",
    url: "",
  },
  {
    id: 8,
    title: "Cookies",
    category: "dessert",
    img: "./images/cookies.jpg",
    desc: "",
  },
  {
    id: 9,
    title: "BlueMoon",
    category: "drink",
    img: "./images/blueMoon.jpg",
    desc: "",
  },
  {
    id: 10,
    title: "Coors Light",
    category: "drink",
    img: "./images/coorslight.png",
    desc: "",
  },
  {
    id: 12,
    title: "Baked Salmon and Asparagus",
    category: "food",
    img: "./images/BakedSalmonwithAs.jpg",
    desc: "",
    url: "https://www.instagram.com/p/Cf53fATOV3h/?igshid=YmMyMTA2M2Y=",
  },
];

export default Data;
